# Generated by Django 4.2.7 on 2025-10-06 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('basketball', 'Basketball'), ('football', 'Football')], default='football', help_text='The sport for the betting scenario', max_length=20)),
                ('team', models.CharField(help_text='The team name', max_length=100)),
                ('player', models.CharField(help_text='The player name', max_length=100)),
                ('bet_type', models.CharField(choices=[('over', 'Over'), ('under', 'Under')], help_text='Whether the bet is over or under', max_length=10)),
                ('action', models.CharField(help_text='The action being bet on (e.g., Passing Yards)', max_length=50)),
                ('action_amount', models.DecimalField(decimal_places=1, help_text='The threshold amount for the action', max_digits=10)),
                ('bet_amount', models.DecimalField(decimal_places=2, help_text='The bet amount in dollars', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the betting scenario was created')),
                ('prediction_score', models.FloatField(blank=True, help_text='ML model prediction score (0-1)', null=True)),
                ('confidence_level', models.CharField(blank=True, help_text='Confidence level (Low, Medium, High)', max_length=20, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the scenario has been processed by ML model')),
            ],
            options={
                'verbose_name': 'Betting Scenario',
                'verbose_name_plural': 'Betting Scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
