# Generated by Django 4.2.7 on 2025-10-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(help_text="NFL GSIS ID (e.g., '00-0023459')", max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_index=True, help_text="Full display name (e.g., 'Patrick Mahomes')", max_length=100)),
                ('short_name', models.CharField(blank=True, help_text="Short name (e.g., 'P.Mahomes')", max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End')], db_index=True, help_text='Player position (QB, RB, WR, TE)', max_length=10)),
                ('current_team', models.CharField(blank=True, db_index=True, help_text="Current team abbreviation (e.g., 'KC')", max_length=10, null=True)),
                ('jersey_number', models.IntegerField(blank=True, help_text='Jersey number', null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CUT', 'Cut'), ('DEV', 'Development'), ('RES', 'Reserved'), ('RET', 'Retired'), ('UNK', 'Unknown')], default='UNK', help_text='Player status', max_length=10)),
                ('headshot_url', models.URLField(blank=True, help_text='URL to player headshot image', max_length=500, null=True)),
                ('rookie_season', models.IntegerField(blank=True, null=True)),
                ('last_season', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(db_index=True, help_text='Season year (e.g., 2025)')),
                ('week', models.IntegerField(db_index=True, help_text='Week number (1-18 for regular season)')),
                ('season_type', models.CharField(choices=[('REG', 'Regular Season'), ('POST', 'Playoffs'), ('PRE', 'Preseason')], default='REG', help_text='Type of game', max_length=10)),
                ('team', models.CharField(db_index=True, help_text="Team abbreviation (e.g., 'KC')", max_length=10)),
                ('opponent_team', models.CharField(help_text='Opponent team abbreviation', max_length=10)),
                ('completions', models.IntegerField(blank=True, default=0, null=True)),
                ('attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('passing_yards', models.IntegerField(blank=True, default=0, null=True)),
                ('passing_tds', models.IntegerField(blank=True, default=0, null=True)),
                ('passing_interceptions', models.IntegerField(blank=True, default=0, null=True)),
                ('sacks_suffered', models.IntegerField(blank=True, default=0, null=True)),
                ('passing_epa', models.FloatField(blank=True, help_text='Expected Points Added', null=True)),
                ('passing_2pt_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('carries', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_yards', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_tds', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_fumbles', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_fumbles_lost', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_first_downs', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_epa', models.FloatField(blank=True, null=True)),
                ('rushing_2pt_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('receptions', models.IntegerField(blank=True, default=0, null=True)),
                ('targets', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_yards', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_tds', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_fumbles', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_fumbles_lost', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_first_downs', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_epa', models.FloatField(blank=True, null=True)),
                ('receiving_2pt_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_air_yards', models.IntegerField(blank=True, default=0, null=True)),
                ('receiving_yards_after_catch', models.IntegerField(blank=True, default=0, null=True)),
                ('fantasy_points', models.FloatField(blank=True, null=True)),
                ('fantasy_points_ppr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(help_text='Player this stat line belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='api.player')),
            ],
            options={
                'verbose_name': 'Player Game Stats',
                'verbose_name_plural': 'Player Game Stats',
                'ordering': ['-season', '-week'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['display_name'], name='api_player_display_c2984f_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position', 'current_team'], name='api_player_positio_044cee_idx'),
        ),
        migrations.AddIndex(
            model_name='playergamestats',
            index=models.Index(fields=['player', '-season', '-week'], name='api_playerg_player__23b7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='playergamestats',
            index=models.Index(fields=['season', 'week'], name='api_playerg_season_f938d5_idx'),
        ),
        migrations.AddIndex(
            model_name='playergamestats',
            index=models.Index(fields=['team', 'season', 'week'], name='api_playerg_team_55b6c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playergamestats',
            unique_together={('player', 'season', 'week', 'season_type')},
        ),
    ]
